POST http://fk.zz-test05.pinming.org/api/front/person/findDataReportPlatList.htm
Accept: application/json, text/plain,
Content-Type: application/x-www-form-urlencoded
X-Requested-With: XMLHttpRequest
Cookie:_bp_fg_="y1Oz+iVzHEPOboo8JIbe2w=="; _bp_ff_="3BPj8K3+m6mzECkq22/VcJ4UhXxPmryNqpALIjPvzTqI6FnhbZxLG6L2zohBFLOg66A6YWKZj0wkhfjStiO1ig=="; _site3_f_ue_=lIq19fS8GO85MlbkDBPobujEZUgwLPeJ+ySN1YG567o44yAtOCyuNYVEG4l6rAI2tu39/Cz7ARN2w1KAM1p19ZGNJbTQga+44m9k/XlRGxVbyPcSVPANi2EsMvj8FUomxlB3L8seTlldiqg3mD0+nMFiijt01sJdJVuO/pb8MGSjbM0szSkxjnYOEkdkyz/cGAHsGkK38sNPlBrTuehrvkj2Kznf2ovJdkRoETih2sV3n46CGbkVURK7Vl12G/zsHdzxqkCWgIF97paVdc+uh33fruDO10IkMkZnzx1ZCwpJorULSzz62MBpsTrHdfKT5uCQIR4eMOVTy50o9r4ZFB1CNKnJ9l3iuw1yw+9Vr7A=; JSESSIONID=FBA3B006CF3B36A5AA9497307710AAA3; _site2_f_ue_=18IM8ZVszMeo1f7Y58uO7aDR0f7PO1CmYJr5InnXsRnPaynxqsELx5rCcA0wTSWb0RBBj80Sj84VgyS68aWVAGQ5ZeQx4Z1%2BhWnqPcCJn7IdxQGqVcnXn3B9Yn5P%2BcPfcH4VgkGSIg6%2FccGhKWHghSbu%2FBlG40o6zBpLQN0PecIImYxLvhcBPkUMJIxdYmeQpZDsHhKjMjn%2FozwMZ4CswWDxAF4raKl8BInkoxjFOJDmq6xf0uK57KHF5sP%2Fv03dd436cu%2Bws3oCgJpoVrSyqkA1c7Up3kzzhcrMGVuOpvOdeE%2FWL2xBbJQwpQp42mczZ0OO%2B7jgaiNiT0lffIXXXXSGrQa8PxVEb%2BiNJoBSYh8%3D

query.projectId=2950

###