POST http://localhost:8090/discuss/list
Accept: application/json, text/plain,
Content-Type: application/x-www-form-urlencoded
X-Requested-With: XMLHttpRequest


userId=caeca614906f4b3a9e6cfd352f016e86

###
