POST http://localhost:8090/user/edit
Accept: application/json, text/plain,
Content-Type: application/x-www-form-urlencoded
X-Requested-With: XMLHttpRequest

id=caeca614906f4b3a9e6cfd352f016e86&nickName=方珂111

###
