POST http://localhost:8090/user/register
Accept: application/json, text/plain,
Content-Type: application/x-www-form-urlencoded
X-Requested-With: XMLHttpRequest

userName=fangfangfang&password=123456

###
